### ISSUE TITLE
6.0 Documentation

### ISSUE THREAD

**Issue by msullivan** [geldata/gel#8067]
Things we should probably document:

- [x] SQL DML (Mostly done, but needs some tweaks, 6.0 tagging)
- [x] DML in functions (https://github.com/edgedb/edgedb/pull/7945/)
- [x] SQL over edgedb protocol?
- [x] Path factoring changes (https://github.com/edgedb/edgedb/issues/7766)
- [x] PostGIS (https://github.com/edgedb/edgedb/issues/7412)
- [x] Extension package installation (https://github.com/edgedb/edgedb/pull/7921)
- [x] Auth changes
- [x] Query perf observability and `sys::QueryStats` (https://github.com/edgedb/edgedb/issues/7725)
- [x] `net::http`
- [x] Standard library reorganization (https://github.com/edgedb/edgedb/issues/7737)
